import { Chess } from "https://cdn.jsdelivr.net/npm/chess.js@1/+esm";
import { ENABLE_MULTIPLAYER, firebaseConfig } from "./firebase-config.js";

let dbApi=null,db=null,multiplayerReady=false;
if(ENABLE_MULTIPLAYER){const{initializeApp}=await import("https://www.gstatic.com/firebasejs/10.12.4/firebase-app.js");dbApi=await import("https://www.gstatic.com/firebasejs/10.12.4/firebase-database.js");db=dbApi.getDatabase(initializeApp(firebaseConfig));multiplayerReady=true;}
const $=id=>document.getElementById(id);
const boardEl=$("board"),topClockEl=$("topClock"),bottomClockEl=$("bottomClock"),opponentNameEl=$("opponentName"),opponentColorEl=$("opponentColor"),selfNameEl=$("selfName"),selfColorEl=$("selfColor"),gameStatusEl=$("gameStatus"),connectionStatusEl=$("connectionStatus"),roomCodeEl=$("roomCode"),roomInputEl=$("roomInput"),inviteLinkEl=$("inviteLink"),whiteSeatEl=$("whiteSeat"),blackSeatEl=$("blackSeat"),whiteCapturedEl=$("whiteCaptured"),blackCapturedEl=$("blackCaptured"),moveListEl=$("moveList"),promotionPopoverEl=$("promotionPopover"),promotionPiecesEl=$("promotionPieces");
const START=5*60*1000,VAL={q:9,r:5,b:3,n:3,p:1};
const UNI={wk:"♔",wq:"♕",wr:"♖",wb:"♗",wn:"♘",wp:"♙",bk:"♚",bq:"♛",br:"♜",bb:"♝",bn:"♞",bp:"♟"};
let chess=new Chess(),roomId="",currentRoom=null,myColor=null,orientation="w",selectedSquare=null,legalTargets=[],pendingPromotion=null,unsubscribeRoom=null,timeoutClaim=false;
const clientId=getClientId(),clientName=getClientName();
function getClientId(){let v=localStorage.getItem("woodboard-chess-client-id");if(!v){v=`guest-${crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)}`;localStorage.setItem("woodboard-chess-client-id",v)}return v}
function getClientName(){let v=localStorage.getItem("woodboard-chess-client-name");if(!v){v=`Guest ${Math.floor(1000+Math.random()*9000)}`;localStorage.setItem("woodboard-chess-client-name",v)}return v}
function setStatus(t,k=""){connectionStatusEl.className=`status-box ${k}`;connectionStatusEl.textContent=t}
function now(){return Date.now()}function rr(code=roomId){return dbApi.ref(db,`rooms/${code}`)}function pr(code=roomId){return dbApi.ref(db,`rooms/${code}/presence/${clientId}`)}
function both(r){return !!(r?.players?.white&&r?.players?.black)}function colorName(c){return c==="w"?"White":c==="b"?"Black":"Spectator"}
function initialRoom(white){return{fen:new Chess().fen(),players:{white,black:""},names:{[white]:clientName},clocks:{w:START,b:START,lastTick:now(),running:false},moves:[],result:"",createdAt:now(),updatedAt:now()}}
function localRoom(){return{fen:chess.fen(),players:{white:"local-white",black:"local-black"},names:{"local-white":"White","local-black":"Black"},clocks:{w:START,b:START,lastTick:now(),running:true},moves:[],result:""}}
function mySide(r){if(!r?.players)return null;if(r.players.white===clientId)return"w";if(r.players.black===clientId)return"b";return"spectator"}
function roomLink(code=roomId){return code?`${location.origin}${location.pathname}#${code}`:"Create a room first"}
function randCode(){const a="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";return Array.from({length:6},()=>a[Math.floor(Math.random()*a.length)]).join("")}
function fmt(ms){let s=Math.max(0,Math.ceil(ms/1000));return`${Math.floor(s/60)}:${String(s%60).padStart(2,"0")}`}
function liveClocks(r){if(!r?.clocks)return{w:START,b:START};let w=+r.clocks.w||START,b=+r.clocks.b||START;const g=new Chess(r.fen);if(r.clocks.running===true&&!r.result&&both(r)&&!g.isGameOver()){const e=Math.max(0,now()-(+r.clocks.lastTick||now()));if(g.turn()==="w")w-=e;else b-=e}return{w:Math.max(0,w),b:Math.max(0,b)}}
async function claimTimeout(r,c){if(!multiplayerReady||!roomId||!r||r.result||timeoutClaim||!both(r)||(c.w>0&&c.b>0))return;timeoutClaim=true;await dbApi.runTransaction(rr(roomId),latest=>{if(!latest||latest.result)return latest;const lc=liveClocks(latest);if(lc.w>0&&lc.b>0)return latest;return{...latest,clocks:{...(latest.clocks||{}),w:lc.w,b:lc.b,running:false,lastTick:now()},result:lc.w<=0?"black_wins_time":"white_wins_time",updatedAt:now()}});timeoutClaim=false}
function updateClock(){const r=currentRoom||localRoom(),c=liveClocks(r),top=orientation==="w"?"b":"w",bot=orientation==="w"?"w":"b";topClockEl.textContent=fmt(c[top]);bottomClockEl.textContent=fmt(c[bot]);const active=r.clocks?.running&&both(r)&&!r.result&&!chess.isGameOver();topClockEl.classList.toggle("active",active&&chess.turn()===top);bottomClockEl.classList.toggle("active",active&&chess.turn()===bot);if(c.w<=0||c.b<=0){gameStatusEl.textContent=c.w<=0?"Black wins on time":"White wins on time";claimTimeout(r,c)}}
function files(){return orientation==="w"?["a","b","c","d","e","f","g","h"]:["h","g","f","e","d","c","b","a"]}function ranks(){return orientation==="w"?["8","7","6","5","4","3","2","1"]:["1","2","3","4","5","6","7","8"]}function sq(row,col){return`${files()[col]}${ranks()[row]}`}function light(s){return((s.charCodeAt(0)-96)+(+s[1]))%2===1}
function lastSquares(){const m=currentRoom?.moves||[],l=m[m.length-1];return l?[l.from,l.to]:[]}function king(c){const b=chess.board();for(let r=0;r<8;r++)for(let col=0;col<8;col++){const p=b[r][col];if(p&&p.type==="k"&&p.color===c)return`${"abcdefgh"[col]}${8-r}`}return null}
function piecePath(c,t){return`assets/pieces/${c}${t}.png`}function pieceEl(t,c,mini=false){const code=`${c}${t}`,wrap=document.createElement("span");wrap.className=mini?"mini-piece-holder":"piece";const img=document.createElement("img");img.className=mini?"mini-piece":"piece-img";img.src=piecePath(c,t);img.alt=code;const fb=document.createElement("span");fb.className=`fallback-piece ${c==="b"?"black":"white"}`;fb.textContent=UNI[code]||"?";if(mini){fb.style.fontSize="22px";fb.style.width="26px";fb.style.height="26px"}img.onerror=()=>{img.style.display="none";fb.style.display="grid"};wrap.append(img,fb);return wrap}
function renderBoard(){boardEl.innerHTML="";const fs=files(),rs=ranks(),last=lastSquares(),check=chess.isCheck()?king(chess.turn()):null;for(let r=0;r<8;r++)for(let c=0;c<8;c++){const s=sq(r,c),p=chess.get(s),el=document.createElement("button");el.type="button";el.className=`square ${light(s)?"light":"dark"}`;if(selectedSquare===s)el.classList.add("selected");if(last.includes(s))el.classList.add("last-move");if(legalTargets.includes(s))el.classList.add(p?"capture":"legal");if(check===s)el.classList.add("check");if(c===0){const x=document.createElement("span");x.className="coord rank";x.textContent=rs[r];el.append(x)}if(r===7){const x=document.createElement("span");x.className="coord file";x.textContent=fs[c];el.append(x)}if(p)el.append(pieceEl(p.type,p.color));el.onclick=()=>handleSquare(s);boardEl.append(el)}}
function statusText(){if(currentRoom?.result==="white_wins_time")return"White wins on time";if(currentRoom?.result==="black_wins_time")return"Black wins on time";if(currentRoom?.result?.includes("checkmate"))return currentRoom.result.startsWith("white")?"White wins by checkmate":"Black wins by checkmate";if(currentRoom?.result==="draw")return"Draw";if(multiplayerReady&&roomId&&currentRoom&&!both(currentRoom))return"Waiting for second player";if(chess.isCheckmate())return`${colorName(chess.turn()==="w"?"b":"w")} wins by checkmate`;if(chess.isStalemate())return"Draw by stalemate";if(chess.isThreefoldRepetition())return"Draw by threefold repetition";if(chess.isInsufficientMaterial())return"Draw by insufficient material";if(chess.isDraw())return"Draw";if(chess.isCheck())return`${colorName(chess.turn())} is in check`;return`${colorName(chess.turn())} to move`}
function renderSide(){gameStatusEl.textContent=statusText();roomCodeEl.textContent=roomId||"—";inviteLinkEl.value=roomLink(roomId);const r=currentRoom||localRoom(),top=orientation==="w"?"b":"w",ids=r.players||{},topId=top==="w"?ids.white:ids.black;whiteSeatEl.textContent=ids.white?(r.names?.[ids.white]||"White player"):"Open";blackSeatEl.textContent=ids.black?(r.names?.[ids.black]||"Black player"):"Open";opponentNameEl.textContent=topId?(r.names?.[topId]||"Opponent"):"Waiting...";opponentColorEl.textContent=top==="w"?"White":"Black";selfNameEl.textContent=myColor==="spectator"?"Spectator":clientName;selfColorEl.textContent=myColor==="spectator"?"Spectating":myColor?`Playing as ${colorName(myColor)}`:"Local board";renderCaptured();renderMoves();updateClock()}
function renderMoves(){const m=currentRoom?.moves||[];moveListEl.innerHTML="";for(let i=0;i<m.length;i+=2){const li=document.createElement("li"),n=document.createElement("span");n.className="move-number";n.textContent=`${i/2+1}.`;li.append(n,document.createTextNode(` ${m[i]?.san||""}`));if(m[i+1])li.append(document.createTextNode(`   ${m[i+1].san}`));moveListEl.append(li)}moveListEl.scrollTop=moveListEl.scrollHeight}
function renderCaptured(){const byW=[],byB=[];for(const m of currentRoom?.moves||[]){if(!m.captured)continue;if(m.color==="w")byW.push(m.captured);else byB.push(m.captured)}byW.sort((a,b)=>(VAL[b]||0)-(VAL[a]||0));byB.sort((a,b)=>(VAL[b]||0)-(VAL[a]||0));whiteCapturedEl.innerHTML="";blackCapturedEl.innerHTML="";byW.forEach(t=>whiteCapturedEl.append(pieceEl(t,"b",true)));byB.forEach(t=>blackCapturedEl.append(pieceEl(t,"w",true)))}
function rerender(){renderBoard();renderSide()}function clearSel(){selectedSquare=null;legalTargets=[]}function canMove(){if(!multiplayerReady||!roomId)return true;if(!currentRoom||!both(currentRoom)||currentRoom.result)return false;if(!myColor||myColor==="spectator")return false;return chess.turn()===myColor}
function selectSquare(s){const p=chess.get(s);if(!p||!canMove()||p.color!==chess.turn()||(myColor&&myColor!=="spectator"&&p.color!==myColor))return;selectedSquare=s;legalTargets=chess.moves({square:s,verbose:true}).map(m=>m.to)}
function promoNeeded(f,t){const p=chess.get(f);return !!(p&&p.type==="p"&&((p.color==="w"&&t.endsWith("8"))||(p.color==="b"&&t.endsWith("1"))))}
function showPromo(f,t){pendingPromotion={from:f,to:t};promotionPiecesEl.innerHTML="";const c=chess.get(f).color;for(const pr of["q","r","b","n"]){const b=document.createElement("button");b.type="button";b.className="promotion-piece";b.append(pieceEl(pr,c));b.onclick=async()=>{promotionPopoverEl.classList.add("hidden");const req=pendingPromotion;pendingPromotion=null;await makeMove(req.from,req.to,pr)};promotionPiecesEl.append(b)}promotionPopoverEl.classList.remove("hidden")}
async function handleSquare(s){if(pendingPromotion)return;const clicked=chess.get(s);if(!selectedSquare){selectSquare(s);rerender();return}if(selectedSquare===s){clearSel();rerender();return}if(clicked&&clicked.color===chess.turn()&&canMove()){selectSquare(s);rerender();return}if(!legalTargets.includes(s)){clearSel();rerender();return}if(promoNeeded(selectedSquare,s)){showPromo(selectedSquare,s);return}await makeMove(selectedSquare,s)}
function updateClocksForMove(r,turn){const clocks={...(r.clocks||{})};if(clocks.running&&both(r)){const e=Math.max(0,now()-(+clocks.lastTick||now()));clocks[turn]=Math.max(0,+clocks[turn]-e)}clocks.lastTick=now();clocks.running=both(r);return clocks}
function localMove(f,t,p="q"){const g=new Chess(chess.fen()),m=g.move({from:f,to:t,promotion:p});if(!m)return null;chess=g;currentRoom={...(currentRoom||localRoom()),fen:chess.fen(),moves:[...(currentRoom?.moves||[]),{color:m.color,from:m.from,to:m.to,san:m.san,piece:m.piece,captured:m.captured||"",promotion:m.promotion||""}]};return m}
async function makeMove(f,t,p="q"){if(!canMove()){setStatus("Not your turn, or the second player has not joined yet.","warn");clearSel();rerender();return}if(!multiplayerReady||!roomId){const m=localMove(f,t,p);clearSel();if(!m)setStatus("Illegal move.","warn");rerender();return}await dbApi.runTransaction(rr(roomId),r=>{if(!r||r.result||!both(r))return r;const g=new Chess(r.fen),turn=g.turn();if(turn!==myColor)return r;const lc=liveClocks(r);if(lc[turn]<=0)return{...r,clocks:{...(r.clocks||{}),...lc,running:false,lastTick:now()},result:turn==="w"?"black_wins_time":"white_wins_time",updatedAt:now()};const m=g.move({from:f,to:t,promotion:p});if(!m)return r;const clocks=updateClocksForMove(r,turn);let result="",running=true;if(g.isCheckmate()){result=turn==="w"?"white_wins_checkmate":"black_wins_checkmate";running=false}else if(g.isDraw()){result="draw";running=false}return{...r,fen:g.fen(),clocks:{...clocks,running},result,moves:[...(r.moves||[]),{color:m.color,from:m.from,to:m.to,san:m.san,piece:m.piece,captured:m.captured||"",promotion:m.promotion||""}],updatedAt:now()}});clearSel()}
async function createRoom(){if(!multiplayerReady){setStatus("Multiplayer is OFF. Open firebase-config.js and set ENABLE_MULTIPLAYER to true.","warn");return}await joinRoom(randCode());await copyLink(true)}
async function joinRoom(codeArg){if(!multiplayerReady){setStatus("Multiplayer is OFF. You are using local test mode only.","warn");return}const code=String(codeArg||roomInputEl.value||"").trim().toUpperCase();if(!code){setStatus("Enter a room code first.","warn");return}await dbApi.runTransaction(rr(code),r=>{if(!r)return initialRoom(clientId);const white=r.players?.white||"",black=r.players?.black||"";r.names={...(r.names||{}),[clientId]:clientName};if(white===clientId||black===clientId)return r;if(!white){r.players={...(r.players||{}),white:clientId};r.clocks={...(r.clocks||{}),running:false,lastTick:now()};return r}if(!black){r.players={...(r.players||{}),black:clientId};r.clocks={...(r.clocks||{}),running:true,lastTick:now()};return r}return r});await dbApi.set(pr(code),{id:clientId,name:clientName,joinedAt:now(),lastSeen:now()});try{dbApi.onDisconnect(pr(code)).remove()}catch{}roomId=code;roomInputEl.value=code;location.hash=code;inviteLinkEl.value=roomLink(code);if(unsubscribeRoom)unsubscribeRoom();unsubscribeRoom=dbApi.onValue(rr(code),snap=>{currentRoom=snap.val();if(!currentRoom)return;chess=new Chess(currentRoom.fen);myColor=mySide(currentRoom);if(myColor==="w"||myColor==="b")orientation=myColor;if(!both(currentRoom))setStatus(`Room ${code} ready. You are White. Send the room link to your friend. Timer waits until Black joins.`,"good");else if(myColor==="spectator")setStatus(`Room ${code} opened. White and Black are taken, so you are spectating.`,"good");else setStatus(`Room ${code} connected. You are ${colorName(myColor)}. No login needed.`,"good");clearSel();rerender()})}
async function copyLink(msg=true){if(!roomId){setStatus("Create or join a room first.","warn");return}const url=roomLink(roomId);inviteLinkEl.value=url;try{await navigator.clipboard.writeText(url);if(msg)setStatus("Room link copied. Send it to your friend.","good")}catch{inviteLinkEl.select();if(msg)setStatus("Copy the room link from the box.","warn")}}
function newLocal(){if(unsubscribeRoom)unsubscribeRoom();roomId="";currentRoom=localRoom();chess=new Chess();myColor=null;orientation="w";clearSel();location.hash="";setStatus(multiplayerReady?"Local board reset. Click Create online room link for multiplayer.":"Local mode. Add Firebase Realtime Database config to enable online rooms.",multiplayerReady?"good":"warn");rerender()}
$("createRoomBtn").onclick=createRoom;$("joinRoomBtn").onclick=()=>joinRoom();$("copyLinkBtn").onclick=()=>copyLink(true);$("newLocalBtn").onclick=newLocal;roomInputEl.onkeydown=e=>{if(e.key==="Enter")joinRoom()};$("flipBtn").onclick=()=>{orientation=orientation==="w"?"b":"w";rerender()};setInterval(updateClock,250);currentRoom=localRoom();if(multiplayerReady){setStatus("Online mode ready. Create a room link or open a shared room link.","good");const h=location.hash.replace("#","").trim().toUpperCase();if(h)joinRoom(h)}else setStatus("Local mode. Add Firebase Realtime Database config to enable online rooms.","warn");rerender();
